-- Author: Salvi CF

-- DML 1 solutions

-- 1.
SELECT NOMBRE, APELLIDO1, APELLIDO2, DEPARTAMENTO
FROM PROFESORES
WHERE DEPARTAMENTO = 1;

-- 2.
SELECT NOMBRE, APELLIDO1, APELLIDO2, DEPARTAMENTO
FROM PROFESORES
WHERE DEPARTAMENTO != 3;

-- 3.
SELECT NOMBRE, APELLIDO1, APELLIDO2, EMAIL
FROM PROFESORES
WHERE EMAIL LIKE '%LCC.UMA.ES';

-- 4.
SELECT NOMBRE, APELLIDO1, APELLIDO2,  EMAIL
FROM ALUMNOS
WHERE EMAIL IS NULL;

-- 5.
SELECT NOMBRE, CURSO, TEORICOS, PRACTICOS, TEORICOS+PRACTICOS, (TEORICOS*100)/(TEORICOS+PRACTICOS) "% TEORICO", (PRACTICOS*100)/(TEORICOS+PRACTICOS) "% PRACTICOS"
FROM ASIGNATURAS
WHERE CURSO = 3;

-- otra forma:
SELECT NOMBRE, CREDITOS, ROUND((TEORICOS*100)/(TEORICOS+PRACTICOS), 2) AS TEOR, ROUND((PRACTICOS*100)/(TEORICOS+PRACTICOS), 2) AS PRACT
FROM ASIGNATURAS
WHERE CURSO = 3;
