.set NUMNOTAS, 76
notaFS:
	.word   LA 
	.word   SILEN2
	.word   LA 
	.word   SILEN2
	.word   LA 
	.word   SILEN2
	
	.word   FA 
	.word   DOH
	
	.word   LA
	.word   FA
	.word   DOH
	.word   LA
	
	.word   MIH
	.word   SILEN2
	
	.word   MIH
	.word   SILEN2
	.word   MIH          
	.word   FAH          
	.word   DOH         
	
	.word   SOLs         
	.word   FA            
	.word   DOH         
	.word   LA            

	.word   LAH            
	.word   LA          
	.word   LA         
	.word   LAH 
	.word   SOLHs
	.word   SOLH
	
	.word   FAHs
	.word   FAH
	.word   FAHs
	.word   SILEN
	.word   LAs
	.word   REHs
	.word   REH
	.word   DOHs
	
	.word   DOH
	.word   SI
	.word   DOH
	.word   SILEN
	.word   FA
	.word SOLs
	.word FA
	.word SOLs
	
	.word DOH
	.word LA
	.word DOH
	.word MIH
	
	.word   LAH            
	.word   LA          
	.word   LA         
	.word   LAH 
	.word   SOLHs
	.word   SOLH
	
	
	.word   FAHs
	.word   FAH
	.word   FAHs
	.word   SILEN
	.word   LAs
	.word   REHs
	.word   REH
	.word   DOHs
	
	.word   DOH
	.word   SI
	.word   DOH
	.word   SILEN
	.word   FA
	.word SOLs
	.word FA
	.word SOLs
			
	.word   LA
	.word   FA
	.word   DOH
	.word   LA	
	.word SILEN2

duratFS:	
	.word NG
	.word entre
	.word NG
	.word entre
	.word NG
	.word entre
	.word CORP	
	.word FUS
	
	.word NG
	.word CORP
	.word FUS
	.word BL
	
	.word NG
	.word   entre
	.word NG
	.word   entre
	.word NG
	.word CORP
	.word FUS
	
	.word NG
	.word CORP
	.word FUS
	.word BL

	.word NG  	
	.word CORP   	
	.word FUS   	
	.word NG   	
	.word CORP   	
	.word FUS 
  	
	.word FUS   	
	.word FUS   	
	.word COR   	
	.word COR   	@SILEN
	.word COR   	
	.word NG   	
	.word CORP   	
	.word FUS   	
	
	.word FUS   	
	.word FUS   	
	.word COR
	.word COR      @SILEN
	.word COR
	.word NG
	.word CORP
	.word FUS
	
	.word NG
	.word CORP
	.word FUS
	.word BL

	.word NG  	
	.word CORP   	
	.word FUS   	
	.word NG   	
	.word CORP   	
	.word FUS 
  	
	.word FUS   	
	.word FUS   	
	.word COR   	
	.word COR   	@SILEN
	.word COR   	
	.word NG   	
	.word CORP   	
	.word FUS   	

	.word FUS   	
	.word FUS   	
	.word COR   	
	.word COR   	@SILEN
	.word COR   	
	.word NG   	
	.word CORP   	
	.word FUS   

	.word NG
	.word CORP
	.word FUS
	.word BL
	.word BL

