-- Author: Salvi CF

-- DML 3 solutions

--1----------------------------------------------------------------------------
SELECT D.NOMBRE, COUNT(*) "N� PROFESORES"
FROM DEPARTAMENTOS D, PROFESORES P
WHERE P.DEPARTAMENTO = D.CODIGO
GROUP BY D.NOMBRE;

--2
SELECT D.NOMBRE, SUM(CREDITOS) "CRÉDITOS DEL DEPARTAMENTO"
FROM DEPARTAMENTOS D, ASIGNATURAS A
WHERE D.CODIGO = A.DEPARTAMENTO
GROUP BY D.NOMBRE;

--3
SELECT A.CURSO, COUNT(DISTINCT ALUMNO)
FROM MATRICULAR M, ASIGNATURAS A
WHERE M.ASIGNATURA = A.CODIGO
      AND A.CURSO IS NOT NULL
GROUP BY A.CURSO;

--4
SELECT P.DESPACHO, SUM(I.CARGA_CREDITOS) "TOTAL CREDITOS DESPACHO"
FROM IMPARTIR I, PROFESORES P
WHERE P.ID = I.PROFESOR
      AND DESPACHO IS NOT NULL
GROUP BY P.DESPACHO
;

--5
SELECT M.ASIGNATURA, AVG(DECODE(A.GENERO,'FEM',1,0))*100"PORCENTAJE"
FROM ALUMNOS A, MATRICULAR M
WHERE A.DNI = M.ALUMNO
GROUP BY M.ASIGNATURA
ORDER BY M.ASIGNATURA;

--6
SELECT P.NOMBRE, SUM(M.HOMBRES+M.MUJERES) "POBLACION"
FROM PROVINCIA P, MUNICIPIO M
WHERE P.CODIGO = M.CPRO
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE;

--7
SELECT P.NOMBRE||' '||P.APELLIDO1, D.NOMBRE
FROM PROFESORES P, DEPARTAMENTOS D
WHERE (P.DEPARTAMENTO, P.FECHA_NACIMIENTO) IN (SELECT DEPARTAMENTO, MIN(FECHA_NACIMIENTO)
                                                FROM PROFESORES GROUP BY DEPARTAMENTO)
AND P.DEPARTAMENTO = D.CODIGO;

--8
SELECT DISTINCT AL.NOMBRE||' '||AL.APELLIDO1||' '||AL.APELLIDO2 "ALUMNO", A.NOMBRE "ASIGNATURA"
FROM ALUMNOS AL, MATRICULAR M, ASIGNATURAS A
WHERE AL.DNI = M.ALUMNO
      AND M.ASIGNATURA = A.CODIGO
      AND (A.CREDITOS, AL.DNI) IN (SELECT MAX(A.CREDITOS), M.ALUMNO
                                    FROM MATRICULAR M, ASIGNATURAS A
                                    WHERE M.ASIGNATURA = A.CODIGO
                                    GROUP BY M.ALUMNO);

--9
SELECT D.NOMBRE "DEPARTAMENTO", P.NOMBRE||' '||P.APELLIDO1 "PROFESOR"
FROM PROFESORES P, DEPARTAMENTOS D
WHERE P.DEPARTAMENTO = D.CODIGO
      AND (P.DEPARTAMENTO, P.ANTIGUEDAD) IN (SELECT DEPARTAMENTO, MIN(ANTIGUEDAD)
                                              FROM PROFESORES
                                              GROUP BY DEPARTAMENTO);

--10
SELECT D.NOMBRE, A.NOMBRE
FROM DEPARTAMENTOS D, ASIGNATURAS A
WHERE A.DEPARTAMENTO = D.CODIGO
      AND (D.CODIGO, A.CREDITOS) IN (SELECT DEPARTAMENTO, MIN(CREDITOS)
                                      FROM ASIGNATURAS
                                      GROUP BY DEPARTAMENTO);

--11
SELECT DISTINCT A.NOMBRE "ASIGNATURA", AL.NOMBRE||' '||AL.APELLIDO1||' '||AL.APELLIDO2 "ALUMNO", AL.FECHA_NACIMIENTO "FECHA NACIMIENTO"
FROM ALUMNOS AL, ASIGNATURAS A
WHERE (A.CODIGO, AL.FECHA_NACIMIENTO) IN (SELECT M.ASIGNATURA, MAX(AL.FECHA_NACIMIENTO)
                                          FROM MATRICULAR M, ALUMNOS AL
                                          WHERE CURSO = '14/15' AND AL.DNI = M.ALUMNO
                                          GROUP BY M.ASIGNATURA)
ORDER BY "ASIGNATURA";

--12
SELECT P.NOMBRE||' '||P.APELLIDO1 "PROFESOR", SUM(I.CARGA_CREDITOS)
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR
GROUP BY P.NOMBRE, P.APELLIDO1
HAVING SUM(I.CARGA_CREDITOS) IN (SELECT MAX(SUM(CARGA_CREDITOS))
                                  FROM IMPARTIR
                                  GROUP BY PROFESOR);

--13
SELECT D.NOMBRE "DEPARTAMENTO", COUNT(*) "ASIGNATURAS"
FROM DEPARTAMENTOS D, ASIGNATURAS A
WHERE D.CODIGO = A.DEPARTAMENTO
GROUP BY D.NOMBRE
HAVING COUNT(*) IN (SELECT MAX(COUNT(*))
                    FROM DEPARTAMENTOS D, ASIGNATURAS A
                    WHERE D.CODIGO = A.DEPARTAMENTO
                    GROUP BY D.CODIGO);

--14
SELECT I.PROFESOR, SUM(I.CARGA_CREDITOS) "CREDITOS"
FROM IMPARTIR I
GROUP BY I.PROFESOR
HAVING SUM(I.CARGA_CREDITOS) < 10;


--15
SELECT P.NOMBRE||' '||P.APELLIDO1, SUM(I.CARGA_CREDITOS) "CREDITOS"
FROM IMPARTIR I, PROFESORES P
WHERE I.PROFESOR = P.ID
GROUP BY I.PROFESOR, P.NOMBRE, P.APELLIDO1
HAVING SUM(I.CARGA_CREDITOS) > (SELECT AVG(SUM(I.CARGA_CREDITOS))
                                  FROM IMPARTIR I, PROFESORES P
                                  WHERE I.PROFESOR = P.ID
                                  GROUP BY I.PROFESOR);

--16
SELECT I.PROFESOR, SUM(I.CARGA_CREDITOS)
FROM IMPARTIR I
WHERE CURSO = '15/16'
      AND I.CARGA_CREDITOS < 6.5
GROUP BY I.PROFESOR
HAVING COUNT(*) >= 2;


--18
SELECT D.NOMBRE "DEPARTAMENTO"
FROM DEPARTAMENTOS D
WHERE D.CODIGO NOT IN (SELECT DEPARTAMENTO
                            FROM ASIGNATURAS
                            WHERE CREDITOS >= 7);


--19
SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM PROFESORES P, ASIGNATURAS A, IMPARTIR I
WHERE A.CARACTER = 'OP'
      AND I.PROFESOR = P.ID
      AND I.ASIGNATURA = A.CODIGO
      AND ID NOT IN (SELECT I.PROFESOR
                      FROM IMPARTIR I NATURAL JOIN MATRICULAR M)
ORDER BY P.NOMBRE;

--20
SELECT P1.NOMBRE, P1.APELLIDO1, P2.NOMBRE, P2.APELLIDO1
FROM PROFESORES P1, PROFESORES P2
WHERE NOT EXISTS (SELECT * FROM IMPARTIR I1 NATURAL JOIN MATRICULAR M1, IMPARTIR I2 NATURAL JOIN MATRICULAR M2
                            WHERE I1.PROFESOR = P1.ID
                            AND I2.PROFESOR = P2.ID
                            AND M1.ALUMNO = M2.ALUMNO)
AND P1.ID < P2.ID
ORDER BY P1.NOMBRE;

--21
SELECT P1.NOMBRE||' '||P1.APELLIDO1||' '||P1.APELLIDO2 "PROFESOR 1", P2.NOMBRE||' '||P2.APELLIDO1||' '||P2.APELLIDO2 "PROFESOR 2"
FROM PROFESORES P1, PROFESORES P2
WHERE P1.ID < P2.ID
      AND NOT EXISTS (SELECT *
                      FROM IMPARTIR I1, IMPARTIR I2
                      WHERE I1.PROFESOR = P1.ID
                            AND I2.PROFESOR = P2.ID
                            AND I1.ASIGNATURA = I2.ASIGNATURA);

--22
SELECT A.NOMBRE
FROM ASIGNATURAS A
WHERE A.CODIGO NOT IN (SELECT A.CODIGO
                        FROM ASIGNATURAS A, MATRICULAR M, ALUMNOS AL
                        WHERE A.CODIGO = M.ASIGNATURA
                        AND M.ALUMNO = AL.DNI
                        GROUP BY ASIGNATURA
                        HAVING COUNT(CMUN) > 2);

-- 23
SELECT DISTINCT M.ALUMNO
FROM MATRICULAR M NATURAL JOIN IMPARTIR I
WHERE I.PROFESOR NOT IN (SELECT P.ID
                          FROM PROFESORES P
                          WHERE P.FECHA_NACIMIENTO IN (SELECT MIN(FECHA_NACIMIENTO)
                              FROM PROFESORES));

--24
SELECT M.ALUMNO
FROM MATRICULAR M
WHERE (M.ASIGNATURA, M.GRUPO, M.CURSO) NOT IN(SELECT I.ASIGNATURA, I.GRUPO, I.CURSO
                                              FROM PROFESORES P,DEPARTAMENTOS D, IMPARTIR I
                                              WHERE P.DEPARTAMENTO = D.CODIGO
                                                    AND UPPER(D.NOMBRE) = 'MATEMATICA APLICADA'
                                                    AND I.PROFESOR = P.ID)
GROUP BY M.ALUMNO
HAVING COUNT(*) > 2
ORDER BY M.ALUMNO;

--25
SELECT NOMBRE, CREDITOS, DEPARTAMENTO, CODIGO
FROM ASIGNATURAS
WHERE (CREDITOS, DEPARTAMENTO) IN (SELECT MAX(CREDITOS), DEPARTAMENTO
                                  FROM ASIGNATURAS
                                  WHERE CODIGO NOT IN (SELECT ASIGNATURA
                                                        FROM PROFESORES P, IMPARTIR I
                                                        WHERE TO_DATE('01/01/1970')-FECHA_NACIMIENTO >= 0
                                                        AND I.PROFESOR = P.ID)
                                  GROUP BY DEPARTAMENTO)
      AND CODIGO NOT IN (SELECT ASIGNATURA
                                                        FROM PROFESORES P, IMPARTIR I
                                                        WHERE TO_DATE('01/01/1970')-FECHA_NACIMIENTO >= 0
                                                        AND I.PROFESOR = P.ID)
ORDER BY DEPARTAMENTO;

--26
SELECT A.DEPARTAMENTO, SUM(A.CREDITOS)
FROM ASIGNATURAS A
WHERE A.DEPARTAMENTO IN (SELECT DEPARTAMENTO
                          FROM MATRICULAR M, ASIGNATURAS A
                          WHERE M.ASIGNATURA = A.CODIGO
                          GROUP BY A.DEPARTAMENTO
                          HAVING COUNT(DISTINCT M.ALUMNO) > 10)
GROUP BY A.DEPARTAMENTO
ORDER BY SUM(A.CREDITOS);

--27
SELECT I.PROFESOR, COUNT(*) "CANTIDAD DE ALUMNOS"
FROM IMPARTIR I NATURAL JOIN MATRICULAR M, ALUMNOS AL
WHERE AL.DNI = M.ALUMNO
      AND I.PROFESOR IN (SELECT I.PROFESOR
                          FROM IMPARTIR I, ASIGNATURAS A
                          WHERE I.ASIGNATURA = A.CODIGO
                                AND A.PRACTICOS > A.TEORICOS)


GROUP BY I.PROFESOR;

--28
SELECT A.NOMBRE
FROM ALUMNOS A, MATRICULAR M
WHERE A.DNI = M.ALUMNO
      AND (A.FECHA_PRIM_MATRICULA, M.ASIGNATURA) IN (SELECT MIN(AL.FECHA_PRIM_MATRICULA), M.ASIGNATURA
                                                      FROM ALUMNOS AL, ASIGNATURAS A, MATRICULAR M
                                                      WHERE AL.DNI = M.ALUMNO
                                                            AND A.CODIGO = M.ASIGNATURA
                                                            AND M.ASIGNATURA IN (SELECT M.ASIGNATURA
                                                                                  FROM ALUMNOS A, MATRICULAR M
                                                                                  WHERE A.DNI = M.ALUMNO
                                                                                        AND CURSO = '15/16'
                                                                                  GROUP BY M.ASIGNATURA
                                                                                  HAVING COUNT(*) > 3)
                                      GROUP BY M.ASIGNATURA);

-- ALUMNO M�S ANTIGUO DE CADA ASIGNATURA
SELECT MIN(AL.FECHA_PRIM_MATRICULA), M.ASIGNATURA
FROM ALUMNOS AL, ASIGNATURAS A, MATRICULAR M
WHERE AL.DNI = M.ALUMNO
      AND A.CODIGO = M.ASIGNATURA
GROUP BY M.ASIGNATURA;
--ASIGNATURAS CON MAS DE  3 ALUMNOS EN EL CURSO 15/16
SELECT M.ASIGNATURA
                        FROM ALUMNOS A, MATRICULAR M
                        WHERE A.DNI = M.ALUMNO
                              AND CURSO = '15/16'
                        GROUP BY M.ASIGNATURA
                        HAVING COUNT(*) > 3;

--29
(SELECT A.NOMBRE, COUNT(*)
FROM ASIGNATURAS A, IMPARTIR I
WHERE A.CODIGO IN (SELECT M.ASIGNATURA
                    FROM ASIGNATURAS A,MATRICULAR M
                    WHERE A.CODIGO = M.ASIGNATURA
                    AND M.CURSO = '15/16'
                    AND A.CODIGO IN (SELECT A.CODIGO
                                      FROM DEPARTAMENTOS D1, ASIGNATURAS A
                                      WHERE NOT EXISTS (SELECT * FROM DEPARTAMENTOS D2 WHERE D2.FECHA_CREACION < D1.FECHA_CREACION)
                                          AND A.DEPARTAMENTO = D1.CODIGO)
GROUP BY M.ASIGNATURA
HAVING COUNT(DISTINCT M.ALUMNO) < 16)
AND A.CODIGO = I.ASIGNATURA
AND I.CURSO = '15/16'
GROUP BY A.NOMBRE)

UNION

(SELECT A.NOMBRE, COUNT(NULL)
FROM ASIGNATURAS A
WHERE A.CODIGO IN (SELECT M.ASIGNATURA
                    FROM ASIGNATURAS A,MATRICULAR M
                    WHERE A.CODIGO = M.ASIGNATURA
                    AND M.CURSO = '15/16'
                    AND A.CODIGO IN (SELECT A.CODIGO
                                      FROM DEPARTAMENTOS D1, ASIGNATURAS A
                                      WHERE NOT EXISTS (SELECT * FROM DEPARTAMENTOS D2 WHERE D2.FECHA_CREACION < D1.FECHA_CREACION)
                                          AND A.DEPARTAMENTO = D1.CODIGO)
GROUP BY M.ASIGNATURA
HAVING COUNT(DISTINCT M.ALUMNO) < 16)
AND A.CODIGO NOT IN (SELECT ASIGNATURA FROM IMPARTIR)
GROUP BY A.NOMBRE)
;

--30
SELECT I.PROFESOR
FROM IMPARTIR I
GROUP BY I.PROFESOR
HAVING COUNT(I.ASIGNATURA) >= 2

INTERSECT

SELECT I.PROFESOR
FROM IMPARTIR I NATURAL JOIN MATRICULAR M, ALUMNOS A
WHERE A.DNI = M.ALUMNO
      AND TO_DATE('01/01/1995')-A.FECHA_NACIMIENTO > 0;
